branch-defaults:
  main:
    environment: Flaskcloud-env
environment-defaults:
  Flaskcloud-env:
    branch: main
    repository: flaskcloud
global:
  application_name: Flaskcloud
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
