branch-defaults:
  default:
    environment: Flaskcloud2-env
environment-defaults:
  Flaskcloud2-env:
    branch: null
    repository: null
global:
  application_name: Flaskcloud2
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
